language: csharp
sudo: false

env:
 global:
  - EnableNuGetPackageRestore=true 
  
mono:
  - latest

install:
  - nuget install Cake -Version 0.6.4 -OutputDirectory tools/
script: 
  - mono tools/Cake.0.6.4/Cake.exe build.cake