install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - nuget install Cake -Version 0.6.4 -OutputDirectory tools\

build_script: 
  - ps: build/build.ps1 -Target "Test"

# disable built-in tests.
test: off